### ISSUE TITLE
*.DFI doesn't work for two or more projects

### ISSUE THREAD

**Issue by evshvarov** [intersystems/ipm#254]
If I try to install the second module with *.DFI resource I see the following:
IRISAPP>zpm "install analytics-okr"

ERROR! Resource '*.DFI' is already defined as part of module 'iris-analytics-sample'; cannot also be listed in module 'analytics-okr'
  > ERROR #6315: Errors reporting importing XML subelement in file '/usr/irissys/mgr/.modules/IRISAPP/analytics-okr/1.0.0/module.xml' at line '3' offset '38', skipping this item.
IRISAPP>
Let's free * resources of conflicts with each other?

**Comment by isc-tleavitt** [comment]
The issue here (and with wildcards in general) is tracking packages' ownership of resources. A folder wildcard (as discussed in #381) would be much better. This is critical to embedded source control, which is itself important for IRIS BI use cases as things are most commonly edited through management portal editors.
