### ISSUE TITLE
Load Error if a package contains a coverage.list file for use with TestTools

### ISSUE THREAD

**Issue by ghost** [intersystems/ipm#389]
ERROR! Unable to import file '/home/stefanc/t..../coverage.list' as this is not a supported type.
Is it possible to exclude specific files or file masks from the import section?

**Comment by daimor** [comment]
I need to check, but as far as I remember, this happens on IRIS side, when it loads tests.

**Comment by daimor** [comment]
Could you explain a bit where this file is located, and during which process exactly it tries to be loaded?

**Comment by csoft-sc** [comment]
Hi,

My code is structured in such a way that the Unit Tests are with its applicable package.
For example:
src/MainPackage/MyClass.cls
srsrc/MainPackage/UnitTests/MyClass.cls
The code coverage by testtools is controlled with the coverage.list file in
src/MainPackage/coverage.list

The coverage.list file must be present in the path being scanned for unit tests.

I am not sure if it will help to move all the tests to a different directory like unit-test/

I am testing a new module.xml file.
In a testing namespace I am doing the load -dev -verbose /path/to/module.xml to check that the module file is working correctly and that the compilation completes.

Kind regards,
[upload image]
Stefan Cronje
Director
comprehensoft
M: +27 82 641 1478
W: https://www.comprehensoft.com<https://www.comprehensoft.com/>
E: ***@***.******@***.***>
[linkedin]<https://www.linkedin.com/company/comprehensoft>

IMPORTANT: The contents of this email and any attachments are confidential. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by isc-tleavitt** [comment]
Unit tests should be their own separate resource directory - that will fix the issue.

I have a documentation task for TestCoverage about using alongside IPM (https://github.com/intersystems/TestCoverage/issues/28) and that will be the venue to cover best practices.
