### ISSUE TITLE
Incorect "*.DFI" export/import support

### ISSUE THREAD

**Issue by Frisle** [intersystems/ipm#473]
Not only that syntax is malfunctioned, but all ways of importing/exporting dfi files

All this is not working properly
https://github.com/intersystems/ipm/pull/169

For example

When upload
![Code_dEAEL7ooT7](https://github.com/intersystems/ipm/assets/47441164/e8d8ef29-9d0e-4075-83bd-5e5aeb8aa3b7)

When download and install into another app
![Code_pelJyjfLwp](https://github.com/intersystems/ipm/assets/47441164/aa426c18-9f98-475d-9d07-b76f41944955)

When using Resourse Name="*.DFI"

![Code_X4YqBaUfv4](https://github.com/intersystems/ipm/assets/47441164/a95818a9-b102-4c23-ac03-ed5938200361)

**Comment by isc-tleavitt** [comment]
We really shouldn't declare / allow *.DFI because that says "the current package owns all DFIs in the current namespace" - meaning, if the package is uninstalled, all DFIs should be deleted to clean up. The solution to this is covered in #381.

The other issue, looking for .dfi but not .xml, is incidentally covered in work that will be part of v0.9.0 (the next major release - targeting next month for that). The changes in #466 fix this (and our integration tests properly cover it).

Will leave this open until v0.9.0 is released (that's the point at which it's really "fixed" for your purposes).
