### ISSUE TITLE
(Re?)introduce SASchema for .ZPM document type and update for "unwrapped" format

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/ipm#502]
Somewhat related to #501 - we need to reintroduce SASchema support and ideally expand to cover the "unwrapped" (e.g., top-level <Resource> rather than <Resources>{<Resource></Resource>...}</Resources> - bonus points if we can generate out SASchema for different resource processor types. A challenge may be differentiating attributes based on ProcessorClass - most relevant for non-built-in resource processors like from isc.ipm.js.

**Comment by isc-kiyer** [comment]
This is a good idea for the short term. For the longer term, would be great to support JSON where we can easily define a schema in the github repo and use $schema property to get intellisense which is better than the native XML autocomplete since it doesn't include descriptions of properties, attributes etc. which we can get with JSON.

**Comment by isc-tleavitt** [comment]
This is less valuable for the short term because https://github.com/intersystems/language-server/issues/334 was nixed, so this won't help VSCode users.

**Comment by isc-kiyer** [comment]
When https://github.com/intersystems/ipm/issues/537 is eventually completed, VS code has native support for JSON schemas so can then get good autocompletion

**Comment by isc-tleavitt** [comment]
Because this won't help VSCode users, closing
