### ISSUE TITLE
Ensure WSGI applications (2024.1+) are supported properly in IPM

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/ipm#504]
see https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=GCRN_new20241#GCRN_new20241_dev_wsgi

The existing CSPApplication class should work (assuming %Installer is up-to-date with the new features), but we might want a new resource processor class to make this even easier.

**Comment by isc-kiyer** [comment]
I don't think the %Installer stuff is being kept up to date. Focus has moved to cpf merge so I don't think the Installer stuff. I recommend re-writing the class to not use %Installer and directly wrap around Security.Applications which is the source of truth and always kept up to date.
We could also consider packaging cpf merge files with the package manager and apply those when a package is installed (this could be tricky though since the instance needs to be restarted for this I believe).

**Comment by isc-tleavitt** [comment]
"I don't think the %Installer stuff is being kept up to date." - that was my suspicion too, but you never know. Wrapping Security.Applications makes sense to me.

**Comment by isc-tleavitt** [comment]
@isc-shuliu could you poke around at this a bit when you wrap up the CI? Would be good to have at least doc / a sample of how it works with IPM 0.7.0 by the end of next week.

**Comment by isc-shuliu** [comment]
This issue has been addressed in #519 and future updates will be tracked in #523.
